name: Cron

on:
  schedule:
    - cron: '0 0-14 * * *' # KST 09:00 ~ 23:00
    - cron: '0 15-18 * * *' # KST 00:00 ~ 03:00

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Install Playwright
        run: deno run -A playwright install chromium --with-deps --only-shell
      
      - name: Run main.ts
        run: deno -A main.ts